title: Essential Kit
description: A collection of open-source, privacy-friendly and secure alternatives for the browser extensions that netizens ❤️
author: 
  name: Justice Ogbonna
  email: hello@essentialkit.org

theme: minima

# base_url: /website
# repository: essentialkit/website

# Minima social links
github_username: essentialkit
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
#   - _pages/frontpage.md
#   - _pages/about.md
#   - _pages/archive.md
#   - _pages/extensions.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

collections:
  extensions:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: G-K0JH8L4JRX
